from relation import Relation

checkable_relations = [
    'capital of',
    'capital',
    'mother',
    'father',
    'occupation',
    'official language',
    'place of burial',
    'place of death',
]

checkable_relations = [relation.formal_name() for relation in Relation]

interesting_relations = [
        "position held",
        "date of birth",
        "birthday",
        "commissioned by",
        "illustrator",
        "contributing factor of",
        "cause of destruction",
        "instrumentation",
        "blood type",
        "standards body",
        "convicted of",
        "material used",
        "cause of death",
        "film editor",
        "published in",
        "capital",
        "significant event",
        "award received",
        "main subject",
        "commander of",
        "sports discipline competed in",
        "candidate",
        "anatomical location",
        "legislated by",
        "separated from",
        "producer",
        "cathedral",
        "main building contractor",
        "connects with",
        "nominated for",
        "family name",
        "discoverer or inventor",
        "religion",
        "professorship",
        "officeholder",
        "basin country",
        "home venue",
        "by-product of",
        "airline hub",
        "medical condition treated",
        "enclave within",
        "signatory",
        "filmography",
        "charted in",
        "programmer",
        "original network",
        "depicted by",
        "member of",
        "original combination",
        "head of government",
        "cuisine",
        "pet",
        "playing hand",
        "inspired by",
        "medical specialty",
        "sexual orientation",
        "manager/director",
        "sport",
        "main food source",
        "series",
        "librettist",
        "screenwriter",
        "recorded at",
        "interested in",
        "currency",
        "foundational text",
        "has contributing factor",
        "lyrics by",
        "eye color",
        "instrument",
        "authority",
        "medical treatment",
        "author",
        "participant",
        "list of works",
        "creator", "organizer",
        "hair color",
        "allegiance",
        "approximation algorithm",
        "space group",
        "filming location",
        "manufacturer",
        "professional or sports partner",
        "used by",
        "solves",
        "legal form",
        "follows",
        "genre",
        "has quality",
        "performer",
        "studied by",
        "doctoral thesis",
        "source of energy",
        "exclave of",
        "conferred by",
        "given name",
        "country for sport",
        "anthem",
        "lifestyle",
        "official residence",
        "chairperson",
        "measures",
        "distribution",
        "spouse",
        "flag",
        "ethnic group",
        "partner",
        "distributor",
        "highest point",
        "named after",
        "editor",
        "facet of",
        "official language",
        "killed by",
        "place of burial",
        "platform",
        "work location",
        "investor",
        "manifestation of",
        "field of work",
        "military branch",
        "union of",
        "measured by",
        "replaced by",
        "production designer",
        "country of origin",
        "located on street",
        "country",
        "manner of death",
        "maintained by",
        "operator",
        "sponsor",
        "conflict",
        "child",
        "foods traditionally associated",
        "country of citizenship",
        "academic major",
        "political alignment",
        "side effect",
        "occupation",
        "represented by",
        "depicts",
        "culture",
        "investigated by",
        "notable work",
        "political ideology",
        "sex or gender",
        "educated at",
        "winner",
        "stated in",
        "general manager",
        "native language",
        "chief executive officer",
        "has cause",
        "mother",
        "contributor",
        "designer",
        "member of sports team",
        "choreographer",
        "replaces",
        "place of birth",
        "based on",
        "executive producer",
        "appointed by",
        "production company",
        "capital of",
        "influenced by",
        "place of death",
        "publisher",
        "costume designer",
        "founder",
        "head coach",
        "godparent",
        "participating teams",
        "said to be the same as",
        "noble family",
        "industry",
        "cast member",
        "doctoral student",
        "place of publication",
        "cause of", "constellation",
        "theme music",
        "captain",
        "use",
        "director",
        "dedicated to",
        "league",
        "employer",
        "characters",
        "residence",
        "field of this occupation",
        "owned by",
        "father",
        "owner of",
        "noble title",
        "academic degree",
        "doctoral advisor",
        "student of",
        "student",
        "occupant",
        "member of political party",
        "head of state",
        "product",
        "studies",
        "headquarters location",
        "location",
        "partnership with",
        "participant of",
        "color",
        "architect",
        "deepest point",
]