our_relations = {
    'head of government': 'P6',
    'brother': 'P7',
    'sister': 'P9',
    'sibling': 'P3373',
    'country': 'P17',
    'place of birth': 'P19',
    'place of death': 'P20',
    'sex or gender': 'P21',
    'father': 'P22',
    'mother': 'P25',
    'spouse': 'P26',
    'country of citizenship': 'P27',
    'continent': 'P30',
    'head of state': 'P35',
    'capital': 'P36',
    'currency': 'P38',
    'position held': 'P39',
    'official language': 'P37',
    'child': 'P40',
    'stepfather': 'P43',
    'stepmother': 'P44',
    'author': 'P50',
    'member of sports team': 'P54',
    'director': 'P57',
    'screenwriter': 'P58',
    'alma mater': 'P69',
    'architect': 'P84',
    'composer': 'P86',
    'anthem': 'P85',
    'sexual orientation': 'P91',
    'editor': 'P98',
    'occupation': 'P106',
    'employer': 'P108',
    'founder': 'P112',
    'league': 'P118',
    'place of burial': 'P119',
    'field of work': 'P101',
    'native language': 'P103',
    'cast member': 'P161',
    'award received': 'P166',
    'follows': 'P155',
    'ethnic group': 'P172',
    'religion': 'P140',
    'eye color': 'P1340',
    'capital of': 'P1376',
    'number of children': 'P1971',
    'uncle': '',
    'aunt': '',
    'date of birth': 'P569',
}

relation2impacted_relations = {
    'head of government': ['head of state'],
    'brother': ['sibling'],
    'sister': ['sibling'],
    'sibling': ['brother', 'sister'],
    'country': [],
    'place of birth': ['country of citizenship'],
    'place of death': [],
    'sex or gender': [],
    'father': ['brother', 'sister', 'ethnic group', 'uncle', 'aunt'],
    'mother': ['brother', 'sister', 'ethnic group', 'uncle', 'aunt'],
    'spouse': [],
    'country of citizenship': [],
    'continent': ['country'],
    'head of state': ['head of government'],
    'capital': [],
    'capital of': ['country', 'continent', 'currency', 'official language'],
    'currency': [],
    'position held': [],
    'official language': [],
    'child': ['number of children'],
    'stepfather': [],
    'stepmother': [],
    'author': [],
    'member of sports team': [],
    'director': [],
    'screenwriter': [],
    'alma mater': [],
    'architect': [],
    'composer': [],
    'anthem': [],
    'sexual orientation': [],
    'editor': [],
    'occupation': ['field of work'],
    'employer': [],
    'founder': [],
    'league': [],
    'place of burial': [],
    'field of work': ['occupation'],
    'native language': [],
    'cast member': [],
    'award received': [],
    'follows': [],
    'ethnic group': [],
    'religion': [],
    'eye color': [],
    'number of children': [],
    'uncle': [],
    'aunt': [],
    'date of birth': [],
}


relation2phrase = {
    'head of government': 'The head of government of <subject> is',
    'brother': 'The brother of <subject> is',
    'sister': 'The sister of <subject> is',
    'sibling': "<subject>'s siblings are",
    'country': 'The country which <subject> is associated with is',
    'place of birth': 'The city in which <subject> was born is',
    'place of death': 'The city in which <subject> died is',
    'sex or gender': "<subject>'s gender is",
    'father': 'The father of <subject> is',
    'mother': 'The mother of <subject> is',
    'spouse': "<subject>'s spouse is",
    'country of citizenship': 'The country of citizenship of <subject> is',
    'continent': 'The continent which <subject> is part of is',
    'head of state': 'The head of state of <subject> is',
    'capital': 'The capital of <subject> is',
    'currency': 'The currency in <subject> is',
    'position held': 'The position that has been held by <subject> is',
    'official language': 'The official language of <subject> is',
    'child': 'The child of <subject> is',
    'stepfather': 'The stepfather of <subject> is',
    'stepmother': 'The stepmother of <subject> is',
    'author': 'The author of <subject> is',
    'member of sports team': '<subject> has been a member of a sports team. This team is',
    'director': 'The director of <subject> is',
    'screenwriter': 'The screenwriter of <subject> is',
    'alma mater': '<subject> has been educated at',
    'architect': 'The architect of <subject> is',
    'composer': 'The composer of <subject> is',
    'anthem': 'The anthem of <subject> is',
    'sexual orientation': "<subject>'s sexual orientation is",
    'editor': 'The editor of <subject> is',
    'occupation': 'The occupation of <subject> is',
    'employer': "<subject>'s employer is",
    'founder': 'The founder of <subject> is',
    'league': 'The league in which <subject> plays is',
    'place of burial': 'The country in which <subject> is buried is',
    'field of work': '<subject> has been working in the field of',
    'native language': 'The mother tongue of <subject> is',
    'cast member': "<subject>'s cast members are",
    'award received': '<subject> has won the award of',
    'follows': '<subject> follows',
    'ethnic group': 'The ethnic group which <subject> is associated with is',
    'religion': 'The religion which <subject> is associated with is',
    'eye color': 'The eye color of <subject> is',
    'capital of': '<subject> is the capital of',
    'number of children': 'The number of children <subject> has is',
    'uncle': 'The uncle of <subject> is',
    'aunt': 'The aunt of <subject> is',
    'date of birth': 'The date in which <subject> was born in is'
}
