from relation import Relation

MOTHER_OF_PHRASE = "the mother of <subject>"
FATHER_OF_PHRASE = "the father of <subject>"
SPOUSE_OF_PHRASE = "the spouse of <subject>"
STEPMOTHER_OF_PHRASE = "the step mother of <subject>"
STEPFATHER_OF_PHRASE = "the step father of <subject>"
HEAD_OF_GOVERNMENT_OF_PHRASE = "the head of government of <subject>"
HEAD_OF_STATE_OF_PHRASE = "the head of state of <subject>"
AUTHOR_OF_PHRASE = "the author of <subject>"
EDITOR_OF_PHRASE = "the editor of <subject>"
DIRECTOR_OF_PHRASE = "the director of <subject>"
SCREENWRITER_OF_PHRASE = "the screenwriter of <subject>"
ARCHITECT_OF_PHRASE = "the architect of <subject>"
COMPOSER_OF_PHRASE = "the composer of <subject>"
FOUNDER_OF_PHRASE = "the founder of <subject>"
COUNTRY_OF_PHRASE = "the country <subject> is associated with"
PLACE_OF_BIRTH_OF_PHRASE = "the place of birth of <subject>"
PLACE_OF_DEATH_OF_PHRASE = "the place of death of <subject>"
PLACE_OF_BURIAL_OF_PHRASE = "the place of burial of <subject>"
COUNTRY_OF_CITIZENSHIP_OF_PHRASE = "the country of citizenship of <subject>"
CAPITAL_OF_PHRASE = "the country which <subject> is the capital of"
EMPLOYER_OF_PHRASE = "the employer of <subject>"

relation_relation2phrase = {

    f'{Relation.MOTHER.name}-{Relation.MOTHER.name}': "The name of the maternal grandmother of <subject> is",
    f'{Relation.MOTHER.name}-{Relation.FATHER.name}': "The name of the maternal grandfather of <subject> is",
    f'{Relation.MOTHER.name}-{Relation.BROTHER.name}': "The name of the maternal uncle of <subject> is",
    f'{Relation.MOTHER.name}-{Relation.SISTER.name}': "The name of the maternal aunt of <subject> is",
    f'{Relation.MOTHER.name}-{Relation.SIBLING.name}': Relation.SIBLING.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.SPOUSE.name}': Relation.SPOUSE.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.UNCLE.name}': "The name of the maternal great uncle of <subject> is",
    f'{Relation.MOTHER.name}-{Relation.AUNT.name}': "The name of the maternal great aunt of <subject> is",
    f'{Relation.MOTHER.name}-{Relation.CHILD.name}': Relation.CHILD.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.NUMBER_OF_CHILDREN.name}': Relation.NUMBER_OF_CHILDREN.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.SEX_OR_GENDER.name}': Relation.SEX_OR_GENDER.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.PLACE_OF_BIRTH.name}': Relation.PLACE_OF_BIRTH.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.PLACE_OF_DEATH.name}': Relation.PLACE_OF_DEATH.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.COUNTRY.name}': Relation.COUNTRY.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.COUNTRY_OF_CITIZENSHIP.name}': Relation.COUNTRY_OF_CITIZENSHIP.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.POSITION_HELD.name}': Relation.POSITION_HELD.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.STEPFATHER.name}': "The name of the maternal step grandfather of <subject> is",
    f'{Relation.MOTHER.name}-{Relation.STEPMOTHER.name}': "The name of the maternal step grandmother of <subject> is",
    f'{Relation.MOTHER.name}-{Relation.MEMBER_OF_SPORTS_TEAM.name}': Relation.MEMBER_OF_SPORTS_TEAM.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.ALMA_MATER.name}': Relation.ALMA_MATER.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.SEXUAL_ORIENTATION.name}': Relation.SEXUAL_ORIENTATION.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.OCCUPATION.name}': Relation.OCCUPATION.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.EMPLOYER.name}': Relation.EMPLOYER.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.LEAGUE.name}': Relation.LEAGUE.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.PLACE_OF_BURIAL.name}': Relation.PLACE_OF_BURIAL.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.FIELD_OF_WORK.name}': Relation.FIELD_OF_WORK.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.NATIVE_LANGUAGE.name}': Relation.NATIVE_LANGUAGE.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.AWARD_RECEIVED.name}': Relation.AWARD_RECEIVED.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.FOLLOWS.name}': Relation.FOLLOWS.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.ETHNIC_GROUP.name}': Relation.ETHNIC_GROUP.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.RELIGION.name}': Relation.RELIGION.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.EYE_COLOR.name}': Relation.EYE_COLOR.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.DATE_OF_BIRTH.name}': Relation.DATE_OF_BIRTH.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.DATE_OF_DEATH.name}': Relation.DATE_OF_DEATH.phrase(MOTHER_OF_PHRASE),
    f'{Relation.MOTHER.name}-{Relation.IS_ALIVE.name}': Relation.IS_ALIVE.phrase(MOTHER_OF_PHRASE),

    f'{Relation.FATHER.name}-{Relation.MOTHER.name}': "The name of the paternal grandmother of <subject> is",
    f'{Relation.FATHER.name}-{Relation.FATHER.name}': "The name of the paternal grandfather of <subject> is",
    f'{Relation.FATHER.name}-{Relation.BROTHER.name}': "The name of the paternal uncle of <subject> is",
    f'{Relation.FATHER.name}-{Relation.SISTER.name}': "The name of the paternal aunt of <subject> is",
    f'{Relation.FATHER.name}-{Relation.SIBLING.name}': Relation.SIBLING.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.SPOUSE.name}': Relation.SPOUSE.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.UNCLE.name}': "The name of the paternal great uncle of <subject> is",
    f'{Relation.FATHER.name}-{Relation.AUNT.name}': "The name of the paternal great aunt of <subject> is",
    f'{Relation.FATHER.name}-{Relation.CHILD.name}': Relation.CHILD.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.NUMBER_OF_CHILDREN.name}': Relation.NUMBER_OF_CHILDREN.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.SEX_OR_GENDER.name}': Relation.SEX_OR_GENDER.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.PLACE_OF_BIRTH.name}': Relation.PLACE_OF_BIRTH.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.PLACE_OF_DEATH.name}': Relation.PLACE_OF_DEATH.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.COUNTRY.name}': Relation.COUNTRY.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.COUNTRY_OF_CITIZENSHIP.name}': Relation.COUNTRY_OF_CITIZENSHIP.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.POSITION_HELD.name}': Relation.POSITION_HELD.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.STEPFATHER.name}': "The name of the paternal step grandfather of <subject> is",
    f'{Relation.FATHER.name}-{Relation.STEPMOTHER.name}': "The name of the paternal step grandmother of <subject> is",
    f'{Relation.FATHER.name}-{Relation.MEMBER_OF_SPORTS_TEAM.name}': Relation.MEMBER_OF_SPORTS_TEAM.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.ALMA_MATER.name}': Relation.ALMA_MATER.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.SEXUAL_ORIENTATION.name}': Relation.SEXUAL_ORIENTATION.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.OCCUPATION.name}': Relation.OCCUPATION.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.EMPLOYER.name}': Relation.EMPLOYER.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.LEAGUE.name}': Relation.LEAGUE.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.PLACE_OF_BURIAL.name}': Relation.PLACE_OF_BURIAL.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.FIELD_OF_WORK.name}': Relation.FIELD_OF_WORK.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.NATIVE_LANGUAGE.name}': Relation.NATIVE_LANGUAGE.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.AWARD_RECEIVED.name}': Relation.AWARD_RECEIVED.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.FOLLOWS.name}': Relation.FOLLOWS.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.ETHNIC_GROUP.name}': Relation.ETHNIC_GROUP.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.RELIGION.name}': Relation.RELIGION.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.EYE_COLOR.name}': Relation.EYE_COLOR.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.DATE_OF_BIRTH.name}': Relation.DATE_OF_BIRTH.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.DATE_OF_DEATH.name}': Relation.DATE_OF_DEATH.phrase(FATHER_OF_PHRASE),
    f'{Relation.FATHER.name}-{Relation.IS_ALIVE.name}': Relation.IS_ALIVE.phrase(FATHER_OF_PHRASE),

    f'{Relation.SPOUSE.name}-{Relation.MOTHER.name}': "The name of the mother in law of <subject> is",
    f'{Relation.SPOUSE.name}-{Relation.FATHER.name}': "The name of the father in law of <subject> is",
    f'{Relation.SPOUSE.name}-{Relation.BROTHER.name}': "The name of the brother in law of <subject> is",
    f'{Relation.SPOUSE.name}-{Relation.SISTER.name}': "The name of the sister in law of <subject> is",
    f'{Relation.SPOUSE.name}-{Relation.SIBLING.name}': "The name of the siblings in law of <subject> are",
    f'{Relation.SPOUSE.name}-{Relation.UNCLE.name}': "The name of the uncle in law of <subject> is",
    f'{Relation.SPOUSE.name}-{Relation.AUNT.name}': "The name of the aunt in law of <subject> is",
    f'{Relation.SPOUSE.name}-{Relation.CHILD.name}': Relation.CHILD.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.NUMBER_OF_CHILDREN.name}': Relation.NUMBER_OF_CHILDREN.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.SEX_OR_GENDER.name}': Relation.SEX_OR_GENDER.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.PLACE_OF_BIRTH.name}': Relation.PLACE_OF_BIRTH.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.PLACE_OF_DEATH.name}': Relation.PLACE_OF_DEATH.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.COUNTRY.name}': Relation.COUNTRY.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.COUNTRY_OF_CITIZENSHIP.name}': Relation.COUNTRY_OF_CITIZENSHIP.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.POSITION_HELD.name}': Relation.POSITION_HELD.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.STEPFATHER.name}': Relation.STEPFATHER.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.STEPMOTHER.name}': Relation.STEPMOTHER.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.MEMBER_OF_SPORTS_TEAM.name}': Relation.MEMBER_OF_SPORTS_TEAM.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.ALMA_MATER.name}': Relation.ALMA_MATER.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.SEXUAL_ORIENTATION.name}': Relation.SEXUAL_ORIENTATION.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.OCCUPATION.name}': Relation.OCCUPATION.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.EMPLOYER.name}': Relation.EMPLOYER.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.LEAGUE.name}': Relation.LEAGUE.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.PLACE_OF_BURIAL.name}': Relation.PLACE_OF_BURIAL.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.FIELD_OF_WORK.name}': Relation.FIELD_OF_WORK.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.NATIVE_LANGUAGE.name}': Relation.NATIVE_LANGUAGE.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.AWARD_RECEIVED.name}': Relation.AWARD_RECEIVED.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.FOLLOWS.name}': Relation.FOLLOWS.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.ETHNIC_GROUP.name}': Relation.ETHNIC_GROUP.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.RELIGION.name}': Relation.RELIGION.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.EYE_COLOR.name}': Relation.EYE_COLOR.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.DATE_OF_BIRTH.name}': Relation.DATE_OF_BIRTH.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.DATE_OF_DEATH.name}': Relation.DATE_OF_DEATH.phrase(SPOUSE_OF_PHRASE),
    f'{Relation.SPOUSE.name}-{Relation.IS_ALIVE.name}': Relation.IS_ALIVE.phrase(SPOUSE_OF_PHRASE),

    f'{Relation.STEPMOTHER.name}-{Relation.MOTHER.name}': Relation.MOTHER.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.FATHER.name}': Relation.FATHER.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.BROTHER.name}': Relation.BROTHER.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.SISTER.name}': Relation.SISTER.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.SIBLING.name}': Relation.SIBLING.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.SPOUSE.name}': Relation.SPOUSE.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.UNCLE.name}': Relation.UNCLE.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.AUNT.name}': Relation.AUNT.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.CHILD.name}': Relation.CHILD.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.NUMBER_OF_CHILDREN.name}': Relation.NUMBER_OF_CHILDREN.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.SEX_OR_GENDER.name}': Relation.SEX_OR_GENDER.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.PLACE_OF_BIRTH.name}': Relation.PLACE_OF_BIRTH.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.PLACE_OF_DEATH.name}': Relation.PLACE_OF_DEATH.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.COUNTRY.name}': Relation.COUNTRY.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.COUNTRY_OF_CITIZENSHIP.name}': Relation.COUNTRY_OF_CITIZENSHIP.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.POSITION_HELD.name}': Relation.POSITION_HELD.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.STEPFATHER.name}': Relation.STEPFATHER.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.STEPMOTHER.name}': Relation.STEPMOTHER.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.MEMBER_OF_SPORTS_TEAM.name}': Relation.MEMBER_OF_SPORTS_TEAM.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.ALMA_MATER.name}': Relation.ALMA_MATER.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.SEXUAL_ORIENTATION.name}': Relation.SEXUAL_ORIENTATION.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.OCCUPATION.name}': Relation.OCCUPATION.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.EMPLOYER.name}': Relation.EMPLOYER.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.LEAGUE.name}': Relation.LEAGUE.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.PLACE_OF_BURIAL.name}': Relation.PLACE_OF_BURIAL.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.FIELD_OF_WORK.name}': Relation.FIELD_OF_WORK.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.NATIVE_LANGUAGE.name}': Relation.NATIVE_LANGUAGE.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.AWARD_RECEIVED.name}': Relation.AWARD_RECEIVED.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.FOLLOWS.name}': Relation.FOLLOWS.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.ETHNIC_GROUP.name}': Relation.ETHNIC_GROUP.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.RELIGION.name}': Relation.RELIGION.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.EYE_COLOR.name}': Relation.EYE_COLOR.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.DATE_OF_BIRTH.name}': Relation.DATE_OF_BIRTH.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.DATE_OF_DEATH.name}': Relation.DATE_OF_DEATH.phrase(STEPMOTHER_OF_PHRASE),
    f'{Relation.STEPMOTHER.name}-{Relation.IS_ALIVE.name}': Relation.IS_ALIVE.phrase(STEPMOTHER_OF_PHRASE),

    f'{Relation.STEPFATHER.name}-{Relation.MOTHER.name}': Relation.MOTHER.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.FATHER.name}': Relation.FATHER.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.BROTHER.name}': Relation.BROTHER.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.SISTER.name}': Relation.SISTER.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.SIBLING.name}': Relation.SIBLING.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.SPOUSE.name}': Relation.SPOUSE.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.UNCLE.name}': Relation.UNCLE.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.AUNT.name}': Relation.AUNT.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.CHILD.name}': Relation.CHILD.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.NUMBER_OF_CHILDREN.name}': Relation.NUMBER_OF_CHILDREN.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.SEX_OR_GENDER.name}': Relation.SEX_OR_GENDER.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.PLACE_OF_BIRTH.name}': Relation.PLACE_OF_BIRTH.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.PLACE_OF_DEATH.name}': Relation.PLACE_OF_DEATH.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.COUNTRY.name}': Relation.COUNTRY.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.COUNTRY_OF_CITIZENSHIP.name}': Relation.COUNTRY_OF_CITIZENSHIP.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.POSITION_HELD.name}': Relation.POSITION_HELD.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.STEPFATHER.name}': Relation.STEPFATHER.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.STEPMOTHER.name}': Relation.STEPMOTHER.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.MEMBER_OF_SPORTS_TEAM.name}': Relation.MEMBER_OF_SPORTS_TEAM.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.ALMA_MATER.name}': Relation.ALMA_MATER.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.SEXUAL_ORIENTATION.name}': Relation.SEXUAL_ORIENTATION.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.OCCUPATION.name}': Relation.OCCUPATION.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.EMPLOYER.name}': Relation.EMPLOYER.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.LEAGUE.name}': Relation.LEAGUE.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.PLACE_OF_BURIAL.name}': Relation.PLACE_OF_BURIAL.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.FIELD_OF_WORK.name}': Relation.FIELD_OF_WORK.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.NATIVE_LANGUAGE.name}': Relation.NATIVE_LANGUAGE.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.AWARD_RECEIVED.name}': Relation.AWARD_RECEIVED.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.FOLLOWS.name}': Relation.FOLLOWS.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.ETHNIC_GROUP.name}': Relation.ETHNIC_GROUP.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.RELIGION.name}': Relation.RELIGION.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.EYE_COLOR.name}': Relation.EYE_COLOR.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.DATE_OF_BIRTH.name}': Relation.DATE_OF_BIRTH.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.DATE_OF_DEATH.name}': Relation.DATE_OF_DEATH.phrase(STEPFATHER_OF_PHRASE),
    f'{Relation.STEPFATHER.name}-{Relation.IS_ALIVE.name}': Relation.IS_ALIVE.phrase(STEPFATHER_OF_PHRASE),

    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.MOTHER.name}': Relation.MOTHER.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.FATHER.name}': Relation.FATHER.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.BROTHER.name}': Relation.BROTHER.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.SISTER.name}': Relation.SISTER.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.SIBLING.name}': Relation.SIBLING.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.SPOUSE.name}': Relation.SPOUSE.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.UNCLE.name}': Relation.UNCLE.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.AUNT.name}': Relation.AUNT.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.CHILD.name}': Relation.CHILD.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.NUMBER_OF_CHILDREN.name}': Relation.NUMBER_OF_CHILDREN.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.SEX_OR_GENDER.name}': Relation.SEX_OR_GENDER.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.PLACE_OF_BIRTH.name}': Relation.PLACE_OF_BIRTH.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.PLACE_OF_DEATH.name}': Relation.PLACE_OF_DEATH.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.COUNTRY.name}': Relation.COUNTRY.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.COUNTRY_OF_CITIZENSHIP.name}': Relation.COUNTRY_OF_CITIZENSHIP.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.POSITION_HELD.name}': Relation.POSITION_HELD.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.STEPFATHER.name}': Relation.STEPFATHER.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.STEPMOTHER.name}': Relation.STEPMOTHER.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.MEMBER_OF_SPORTS_TEAM.name}': Relation.MEMBER_OF_SPORTS_TEAM.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.ALMA_MATER.name}': Relation.ALMA_MATER.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.SEXUAL_ORIENTATION.name}': Relation.SEXUAL_ORIENTATION.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.OCCUPATION.name}': Relation.OCCUPATION.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.EMPLOYER.name}': Relation.EMPLOYER.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.LEAGUE.name}': Relation.LEAGUE.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.PLACE_OF_BURIAL.name}': Relation.PLACE_OF_BURIAL.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.FIELD_OF_WORK.name}': Relation.FIELD_OF_WORK.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.NATIVE_LANGUAGE.name}': Relation.NATIVE_LANGUAGE.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.AWARD_RECEIVED.name}': Relation.AWARD_RECEIVED.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.FOLLOWS.name}': Relation.FOLLOWS.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.ETHNIC_GROUP.name}': Relation.ETHNIC_GROUP.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.RELIGION.name}': Relation.RELIGION.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.EYE_COLOR.name}': Relation.EYE_COLOR.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.DATE_OF_BIRTH.name}': Relation.DATE_OF_BIRTH.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.DATE_OF_DEATH.name}': Relation.DATE_OF_DEATH.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),
    f'{Relation.HEAD_OF_GOVERNMENT.name}-{Relation.IS_ALIVE.name}': Relation.IS_ALIVE.phrase(HEAD_OF_GOVERNMENT_OF_PHRASE),

    f'{Relation.HEAD_OF_STATE.name}-{Relation.MOTHER.name}': Relation.MOTHER.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.FATHER.name}': Relation.FATHER.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.BROTHER.name}': Relation.BROTHER.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.SISTER.name}': Relation.SISTER.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.SIBLING.name}': Relation.SIBLING.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.SPOUSE.name}': Relation.SPOUSE.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.UNCLE.name}': Relation.UNCLE.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.AUNT.name}': Relation.AUNT.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.CHILD.name}': Relation.CHILD.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.NUMBER_OF_CHILDREN.name}': Relation.NUMBER_OF_CHILDREN.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.SEX_OR_GENDER.name}': Relation.SEX_OR_GENDER.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.PLACE_OF_BIRTH.name}': Relation.PLACE_OF_BIRTH.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.PLACE_OF_DEATH.name}': Relation.PLACE_OF_DEATH.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.COUNTRY.name}': Relation.COUNTRY.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.COUNTRY_OF_CITIZENSHIP.name}': Relation.COUNTRY_OF_CITIZENSHIP.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.POSITION_HELD.name}': Relation.POSITION_HELD.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.STEPFATHER.name}': Relation.STEPFATHER.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.STEPMOTHER.name}': Relation.STEPMOTHER.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.MEMBER_OF_SPORTS_TEAM.name}': Relation.MEMBER_OF_SPORTS_TEAM.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.ALMA_MATER.name}': Relation.ALMA_MATER.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.SEXUAL_ORIENTATION.name}': Relation.SEXUAL_ORIENTATION.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.OCCUPATION.name}': Relation.OCCUPATION.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.EMPLOYER.name}': Relation.EMPLOYER.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.LEAGUE.name}': Relation.LEAGUE.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.PLACE_OF_BURIAL.name}': Relation.PLACE_OF_BURIAL.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.FIELD_OF_WORK.name}': Relation.FIELD_OF_WORK.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.NATIVE_LANGUAGE.name}': Relation.NATIVE_LANGUAGE.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.AWARD_RECEIVED.name}': Relation.AWARD_RECEIVED.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.FOLLOWS.name}': Relation.FOLLOWS.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.ETHNIC_GROUP.name}': Relation.ETHNIC_GROUP.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.RELIGION.name}': Relation.RELIGION.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.EYE_COLOR.name}': Relation.EYE_COLOR.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.DATE_OF_BIRTH.name}': Relation.DATE_OF_BIRTH.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.DATE_OF_DEATH.name}': Relation.DATE_OF_DEATH.phrase(HEAD_OF_STATE_OF_PHRASE),
    f'{Relation.HEAD_OF_STATE.name}-{Relation.IS_ALIVE.name}': Relation.IS_ALIVE.phrase(HEAD_OF_STATE_OF_PHRASE),

    f'{Relation.AUTHOR.name}-{Relation.MOTHER.name}': Relation.MOTHER.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.FATHER.name}': Relation.FATHER.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.BROTHER.name}': Relation.BROTHER.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.SISTER.name}': Relation.SISTER.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.SIBLING.name}': Relation.SIBLING.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.SPOUSE.name}': Relation.SPOUSE.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.UNCLE.name}': Relation.UNCLE.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.AUNT.name}': Relation.AUNT.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.CHILD.name}': Relation.CHILD.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.NUMBER_OF_CHILDREN.name}': Relation.NUMBER_OF_CHILDREN.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.SEX_OR_GENDER.name}': Relation.SEX_OR_GENDER.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.PLACE_OF_BIRTH.name}': Relation.PLACE_OF_BIRTH.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.PLACE_OF_DEATH.name}': Relation.PLACE_OF_DEATH.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.COUNTRY.name}': Relation.COUNTRY.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.COUNTRY_OF_CITIZENSHIP.name}': Relation.COUNTRY_OF_CITIZENSHIP.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.POSITION_HELD.name}': Relation.POSITION_HELD.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.STEPFATHER.name}': Relation.STEPFATHER.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.STEPMOTHER.name}': Relation.STEPMOTHER.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.MEMBER_OF_SPORTS_TEAM.name}': Relation.MEMBER_OF_SPORTS_TEAM.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.ALMA_MATER.name}': Relation.ALMA_MATER.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.SEXUAL_ORIENTATION.name}': Relation.SEXUAL_ORIENTATION.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.OCCUPATION.name}': Relation.OCCUPATION.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.EMPLOYER.name}': Relation.EMPLOYER.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.LEAGUE.name}': Relation.LEAGUE.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.PLACE_OF_BURIAL.name}': Relation.PLACE_OF_BURIAL.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.FIELD_OF_WORK.name}': Relation.FIELD_OF_WORK.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.NATIVE_LANGUAGE.name}': Relation.NATIVE_LANGUAGE.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.AWARD_RECEIVED.name}': Relation.AWARD_RECEIVED.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.FOLLOWS.name}': Relation.FOLLOWS.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.ETHNIC_GROUP.name}': Relation.ETHNIC_GROUP.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.RELIGION.name}': Relation.RELIGION.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.EYE_COLOR.name}': Relation.EYE_COLOR.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.DATE_OF_BIRTH.name}': Relation.DATE_OF_BIRTH.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.DATE_OF_DEATH.name}': Relation.DATE_OF_DEATH.phrase(AUTHOR_OF_PHRASE),
    f'{Relation.AUTHOR.name}-{Relation.IS_ALIVE.name}': Relation.IS_ALIVE.phrase(AUTHOR_OF_PHRASE),

    f'{Relation.EDITOR.name}-{Relation.MOTHER.name}': Relation.MOTHER.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.FATHER.name}': Relation.FATHER.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.BROTHER.name}': Relation.BROTHER.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.SISTER.name}': Relation.SISTER.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.SIBLING.name}': Relation.SIBLING.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.SPOUSE.name}': Relation.SPOUSE.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.UNCLE.name}': Relation.UNCLE.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.AUNT.name}': Relation.AUNT.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.CHILD.name}': Relation.CHILD.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.NUMBER_OF_CHILDREN.name}': Relation.NUMBER_OF_CHILDREN.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.SEX_OR_GENDER.name}': Relation.SEX_OR_GENDER.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.PLACE_OF_BIRTH.name}': Relation.PLACE_OF_BIRTH.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.PLACE_OF_DEATH.name}': Relation.PLACE_OF_DEATH.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.COUNTRY.name}': Relation.COUNTRY.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.COUNTRY_OF_CITIZENSHIP.name}': Relation.COUNTRY_OF_CITIZENSHIP.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.POSITION_HELD.name}': Relation.POSITION_HELD.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.STEPFATHER.name}': Relation.STEPFATHER.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.STEPMOTHER.name}': Relation.STEPMOTHER.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.MEMBER_OF_SPORTS_TEAM.name}': Relation.MEMBER_OF_SPORTS_TEAM.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.ALMA_MATER.name}': Relation.ALMA_MATER.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.SEXUAL_ORIENTATION.name}': Relation.SEXUAL_ORIENTATION.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.OCCUPATION.name}': Relation.OCCUPATION.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.EMPLOYER.name}': Relation.EMPLOYER.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.LEAGUE.name}': Relation.LEAGUE.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.PLACE_OF_BURIAL.name}': Relation.PLACE_OF_BURIAL.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.FIELD_OF_WORK.name}': Relation.FIELD_OF_WORK.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.NATIVE_LANGUAGE.name}': Relation.NATIVE_LANGUAGE.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.AWARD_RECEIVED.name}': Relation.AWARD_RECEIVED.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.FOLLOWS.name}': Relation.FOLLOWS.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.ETHNIC_GROUP.name}': Relation.ETHNIC_GROUP.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.RELIGION.name}': Relation.RELIGION.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.EYE_COLOR.name}': Relation.EYE_COLOR.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.DATE_OF_BIRTH.name}': Relation.DATE_OF_BIRTH.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.DATE_OF_DEATH.name}': Relation.DATE_OF_DEATH.phrase(EDITOR_OF_PHRASE),
    f'{Relation.EDITOR.name}-{Relation.IS_ALIVE.name}': Relation.IS_ALIVE.phrase(EDITOR_OF_PHRASE),

    f'{Relation.DIRECTOR.name}-{Relation.MOTHER.name}': Relation.MOTHER.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.FATHER.name}': Relation.FATHER.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.BROTHER.name}': Relation.BROTHER.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.SISTER.name}': Relation.SISTER.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.SIBLING.name}': Relation.SIBLING.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.SPOUSE.name}': Relation.SPOUSE.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.UNCLE.name}': Relation.UNCLE.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.AUNT.name}': Relation.AUNT.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.CHILD.name}': Relation.CHILD.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.NUMBER_OF_CHILDREN.name}': Relation.NUMBER_OF_CHILDREN.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.SEX_OR_GENDER.name}': Relation.SEX_OR_GENDER.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.PLACE_OF_BIRTH.name}': Relation.PLACE_OF_BIRTH.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.PLACE_OF_DEATH.name}': Relation.PLACE_OF_DEATH.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.COUNTRY.name}': Relation.COUNTRY.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.COUNTRY_OF_CITIZENSHIP.name}': Relation.COUNTRY_OF_CITIZENSHIP.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.POSITION_HELD.name}': Relation.POSITION_HELD.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.STEPFATHER.name}': Relation.STEPFATHER.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.STEPMOTHER.name}': Relation.STEPMOTHER.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.MEMBER_OF_SPORTS_TEAM.name}': Relation.MEMBER_OF_SPORTS_TEAM.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.ALMA_MATER.name}': Relation.ALMA_MATER.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.SEXUAL_ORIENTATION.name}': Relation.SEXUAL_ORIENTATION.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.OCCUPATION.name}': Relation.OCCUPATION.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.EMPLOYER.name}': Relation.EMPLOYER.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.LEAGUE.name}': Relation.LEAGUE.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.PLACE_OF_BURIAL.name}': Relation.PLACE_OF_BURIAL.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.FIELD_OF_WORK.name}': Relation.FIELD_OF_WORK.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.NATIVE_LANGUAGE.name}': Relation.NATIVE_LANGUAGE.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.AWARD_RECEIVED.name}': Relation.AWARD_RECEIVED.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.FOLLOWS.name}': Relation.FOLLOWS.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.ETHNIC_GROUP.name}': Relation.ETHNIC_GROUP.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.RELIGION.name}': Relation.RELIGION.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.EYE_COLOR.name}': Relation.EYE_COLOR.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.DATE_OF_BIRTH.name}': Relation.DATE_OF_BIRTH.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.DATE_OF_DEATH.name}': Relation.DATE_OF_DEATH.phrase(DIRECTOR_OF_PHRASE),
    f'{Relation.DIRECTOR.name}-{Relation.IS_ALIVE.name}': Relation.IS_ALIVE.phrase(DIRECTOR_OF_PHRASE),

    f'{Relation.SCREENWRITER.name}-{Relation.MOTHER.name}': Relation.MOTHER.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.FATHER.name}': Relation.FATHER.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.BROTHER.name}': Relation.BROTHER.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.SISTER.name}': Relation.SISTER.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.SIBLING.name}': Relation.SIBLING.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.SPOUSE.name}': Relation.SPOUSE.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.UNCLE.name}': Relation.UNCLE.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.AUNT.name}': Relation.AUNT.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.CHILD.name}': Relation.CHILD.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.NUMBER_OF_CHILDREN.name}': Relation.NUMBER_OF_CHILDREN.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.SEX_OR_GENDER.name}': Relation.SEX_OR_GENDER.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.PLACE_OF_BIRTH.name}': Relation.PLACE_OF_BIRTH.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.PLACE_OF_DEATH.name}': Relation.PLACE_OF_DEATH.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.COUNTRY.name}': Relation.COUNTRY.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.COUNTRY_OF_CITIZENSHIP.name}': Relation.COUNTRY_OF_CITIZENSHIP.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.POSITION_HELD.name}': Relation.POSITION_HELD.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.STEPFATHER.name}': Relation.STEPFATHER.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.STEPMOTHER.name}': Relation.STEPMOTHER.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.MEMBER_OF_SPORTS_TEAM.name}': Relation.MEMBER_OF_SPORTS_TEAM.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.ALMA_MATER.name}': Relation.ALMA_MATER.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.SEXUAL_ORIENTATION.name}': Relation.SEXUAL_ORIENTATION.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.OCCUPATION.name}': Relation.OCCUPATION.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.EMPLOYER.name}': Relation.EMPLOYER.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.LEAGUE.name}': Relation.LEAGUE.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.PLACE_OF_BURIAL.name}': Relation.PLACE_OF_BURIAL.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.FIELD_OF_WORK.name}': Relation.FIELD_OF_WORK.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.NATIVE_LANGUAGE.name}': Relation.NATIVE_LANGUAGE.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.AWARD_RECEIVED.name}': Relation.AWARD_RECEIVED.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.FOLLOWS.name}': Relation.FOLLOWS.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.ETHNIC_GROUP.name}': Relation.ETHNIC_GROUP.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.RELIGION.name}': Relation.RELIGION.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.EYE_COLOR.name}': Relation.EYE_COLOR.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.DATE_OF_BIRTH.name}': Relation.DATE_OF_BIRTH.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.DATE_OF_DEATH.name}': Relation.DATE_OF_DEATH.phrase(SCREENWRITER_OF_PHRASE),
    f'{Relation.SCREENWRITER.name}-{Relation.IS_ALIVE.name}': Relation.IS_ALIVE.phrase(SCREENWRITER_OF_PHRASE),

    f'{Relation.ARCHITECT.name}-{Relation.MOTHER.name}': Relation.MOTHER.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.FATHER.name}': Relation.FATHER.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.BROTHER.name}': Relation.BROTHER.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.SISTER.name}': Relation.SISTER.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.SIBLING.name}': Relation.SIBLING.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.SPOUSE.name}': Relation.SPOUSE.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.UNCLE.name}': Relation.UNCLE.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.AUNT.name}': Relation.AUNT.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.CHILD.name}': Relation.CHILD.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.NUMBER_OF_CHILDREN.name}': Relation.NUMBER_OF_CHILDREN.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.SEX_OR_GENDER.name}': Relation.SEX_OR_GENDER.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.PLACE_OF_BIRTH.name}': Relation.PLACE_OF_BIRTH.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.PLACE_OF_DEATH.name}': Relation.PLACE_OF_DEATH.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.COUNTRY.name}': Relation.COUNTRY.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.COUNTRY_OF_CITIZENSHIP.name}': Relation.COUNTRY_OF_CITIZENSHIP.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.POSITION_HELD.name}': Relation.POSITION_HELD.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.STEPFATHER.name}': Relation.STEPFATHER.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.STEPMOTHER.name}': Relation.STEPMOTHER.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.MEMBER_OF_SPORTS_TEAM.name}': Relation.MEMBER_OF_SPORTS_TEAM.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.ALMA_MATER.name}': Relation.ALMA_MATER.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.SEXUAL_ORIENTATION.name}': Relation.SEXUAL_ORIENTATION.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.OCCUPATION.name}': Relation.OCCUPATION.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.EMPLOYER.name}': Relation.EMPLOYER.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.LEAGUE.name}': Relation.LEAGUE.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.PLACE_OF_BURIAL.name}': Relation.PLACE_OF_BURIAL.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.FIELD_OF_WORK.name}': Relation.FIELD_OF_WORK.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.NATIVE_LANGUAGE.name}': Relation.NATIVE_LANGUAGE.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.AWARD_RECEIVED.name}': Relation.AWARD_RECEIVED.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.FOLLOWS.name}': Relation.FOLLOWS.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.ETHNIC_GROUP.name}': Relation.ETHNIC_GROUP.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.RELIGION.name}': Relation.RELIGION.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.EYE_COLOR.name}': Relation.EYE_COLOR.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.DATE_OF_BIRTH.name}': Relation.DATE_OF_BIRTH.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.DATE_OF_DEATH.name}': Relation.DATE_OF_DEATH.phrase(ARCHITECT_OF_PHRASE),
    f'{Relation.ARCHITECT.name}-{Relation.IS_ALIVE.name}': Relation.IS_ALIVE.phrase(ARCHITECT_OF_PHRASE),

    f'{Relation.COMPOSER.name}-{Relation.MOTHER.name}': Relation.MOTHER.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.FATHER.name}': Relation.FATHER.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.BROTHER.name}': Relation.BROTHER.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.SISTER.name}': Relation.SISTER.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.SIBLING.name}': Relation.SIBLING.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.SPOUSE.name}': Relation.SPOUSE.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.UNCLE.name}': Relation.UNCLE.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.AUNT.name}': Relation.AUNT.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.CHILD.name}': Relation.CHILD.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.NUMBER_OF_CHILDREN.name}': Relation.NUMBER_OF_CHILDREN.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.SEX_OR_GENDER.name}': Relation.SEX_OR_GENDER.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.PLACE_OF_BIRTH.name}': Relation.PLACE_OF_BIRTH.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.PLACE_OF_DEATH.name}': Relation.PLACE_OF_DEATH.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.COUNTRY.name}': Relation.COUNTRY.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.COUNTRY_OF_CITIZENSHIP.name}': Relation.COUNTRY_OF_CITIZENSHIP.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.POSITION_HELD.name}': Relation.POSITION_HELD.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.STEPFATHER.name}': Relation.STEPFATHER.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.STEPMOTHER.name}': Relation.STEPMOTHER.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.MEMBER_OF_SPORTS_TEAM.name}': Relation.MEMBER_OF_SPORTS_TEAM.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.ALMA_MATER.name}': Relation.ALMA_MATER.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.SEXUAL_ORIENTATION.name}': Relation.SEXUAL_ORIENTATION.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.OCCUPATION.name}': Relation.OCCUPATION.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.EMPLOYER.name}': Relation.EMPLOYER.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.LEAGUE.name}': Relation.LEAGUE.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.PLACE_OF_BURIAL.name}': Relation.PLACE_OF_BURIAL.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.FIELD_OF_WORK.name}': Relation.FIELD_OF_WORK.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.NATIVE_LANGUAGE.name}': Relation.NATIVE_LANGUAGE.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.AWARD_RECEIVED.name}': Relation.AWARD_RECEIVED.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.FOLLOWS.name}': Relation.FOLLOWS.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.ETHNIC_GROUP.name}': Relation.ETHNIC_GROUP.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.RELIGION.name}': Relation.RELIGION.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.EYE_COLOR.name}': Relation.EYE_COLOR.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.DATE_OF_BIRTH.name}': Relation.DATE_OF_BIRTH.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.DATE_OF_DEATH.name}': Relation.DATE_OF_DEATH.phrase(COMPOSER_OF_PHRASE),
    f'{Relation.COMPOSER.name}-{Relation.IS_ALIVE.name}': Relation.IS_ALIVE.phrase(COMPOSER_OF_PHRASE),

    f'{Relation.FOUNDER.name}-{Relation.MOTHER.name}': Relation.MOTHER.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.FATHER.name}': Relation.FATHER.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.BROTHER.name}': Relation.BROTHER.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.SISTER.name}': Relation.SISTER.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.SIBLING.name}': Relation.SIBLING.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.SPOUSE.name}': Relation.SPOUSE.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.UNCLE.name}': Relation.UNCLE.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.AUNT.name}': Relation.AUNT.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.CHILD.name}': Relation.CHILD.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.NUMBER_OF_CHILDREN.name}': Relation.NUMBER_OF_CHILDREN.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.SEX_OR_GENDER.name}': Relation.SEX_OR_GENDER.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.PLACE_OF_BIRTH.name}': Relation.PLACE_OF_BIRTH.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.PLACE_OF_DEATH.name}': Relation.PLACE_OF_DEATH.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.COUNTRY.name}': Relation.COUNTRY.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.COUNTRY_OF_CITIZENSHIP.name}': Relation.COUNTRY_OF_CITIZENSHIP.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.POSITION_HELD.name}': Relation.POSITION_HELD.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.STEPFATHER.name}': Relation.STEPFATHER.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.STEPMOTHER.name}': Relation.STEPMOTHER.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.MEMBER_OF_SPORTS_TEAM.name}': Relation.MEMBER_OF_SPORTS_TEAM.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.ALMA_MATER.name}': Relation.ALMA_MATER.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.SEXUAL_ORIENTATION.name}': Relation.SEXUAL_ORIENTATION.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.OCCUPATION.name}': Relation.OCCUPATION.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.EMPLOYER.name}': Relation.EMPLOYER.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.LEAGUE.name}': Relation.LEAGUE.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.PLACE_OF_BURIAL.name}': Relation.PLACE_OF_BURIAL.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.FIELD_OF_WORK.name}': Relation.FIELD_OF_WORK.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.NATIVE_LANGUAGE.name}': Relation.NATIVE_LANGUAGE.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.AWARD_RECEIVED.name}': Relation.AWARD_RECEIVED.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.FOLLOWS.name}': Relation.FOLLOWS.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.ETHNIC_GROUP.name}': Relation.ETHNIC_GROUP.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.RELIGION.name}': Relation.RELIGION.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.EYE_COLOR.name}': Relation.EYE_COLOR.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.DATE_OF_BIRTH.name}': Relation.DATE_OF_BIRTH.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.DATE_OF_DEATH.name}': Relation.DATE_OF_DEATH.phrase(FOUNDER_OF_PHRASE),
    f'{Relation.FOUNDER.name}-{Relation.IS_ALIVE.name}': Relation.IS_ALIVE.phrase(FOUNDER_OF_PHRASE),

    f'{Relation.PLACE_OF_BIRTH.name}-{Relation.HEAD_OF_GOVERNMENT.name}': Relation.HEAD_OF_GOVERNMENT.phrase(PLACE_OF_BIRTH_OF_PHRASE),
    f'{Relation.PLACE_OF_BIRTH.name}-{Relation.HEAD_OF_STATE.name}': Relation.HEAD_OF_STATE.phrase(PLACE_OF_BIRTH_OF_PHRASE),
    f'{Relation.PLACE_OF_BIRTH.name}-{Relation.CONTINENT.name}': Relation.CONTINENT.phrase(PLACE_OF_BIRTH_OF_PHRASE),
    f'{Relation.PLACE_OF_BIRTH.name}-{Relation.CAPITAL.name}': Relation.CAPITAL.phrase(PLACE_OF_BIRTH_OF_PHRASE),
    f'{Relation.PLACE_OF_BIRTH.name}-{Relation.CURRENCY.name}': Relation.CURRENCY.phrase(PLACE_OF_BIRTH_OF_PHRASE),
    f'{Relation.PLACE_OF_BIRTH.name}-{Relation.OFFICIAL_LANGUAGE.name}': Relation.OFFICIAL_LANGUAGE.phrase(PLACE_OF_BIRTH_OF_PHRASE),
    f'{Relation.PLACE_OF_BIRTH.name}-{Relation.ANTHEM.name}': Relation.ANTHEM.phrase(PLACE_OF_BIRTH_OF_PHRASE),

    f'{Relation.PLACE_OF_DEATH.name}-{Relation.HEAD_OF_GOVERNMENT.name}': Relation.HEAD_OF_GOVERNMENT.phrase(PLACE_OF_DEATH_OF_PHRASE),
    f'{Relation.PLACE_OF_DEATH.name}-{Relation.HEAD_OF_STATE.name}': Relation.HEAD_OF_STATE.phrase(PLACE_OF_DEATH_OF_PHRASE),
    f'{Relation.PLACE_OF_DEATH.name}-{Relation.CONTINENT.name}': Relation.CONTINENT.phrase(PLACE_OF_DEATH_OF_PHRASE),
    f'{Relation.PLACE_OF_DEATH.name}-{Relation.CAPITAL.name}': Relation.CAPITAL.phrase(PLACE_OF_DEATH_OF_PHRASE),
    f'{Relation.PLACE_OF_DEATH.name}-{Relation.CURRENCY.name}': Relation.CURRENCY.phrase(PLACE_OF_DEATH_OF_PHRASE),
    f'{Relation.PLACE_OF_DEATH.name}-{Relation.OFFICIAL_LANGUAGE.name}': Relation.OFFICIAL_LANGUAGE.phrase(PLACE_OF_DEATH_OF_PHRASE),
    f'{Relation.PLACE_OF_DEATH.name}-{Relation.ANTHEM.name}': Relation.ANTHEM.phrase(PLACE_OF_DEATH_OF_PHRASE),

    f'{Relation.PLACE_OF_BURIAL.name}-{Relation.HEAD_OF_GOVERNMENT.name}': Relation.HEAD_OF_GOVERNMENT.phrase(PLACE_OF_BURIAL_OF_PHRASE),
    f'{Relation.PLACE_OF_BURIAL.name}-{Relation.HEAD_OF_STATE.name}': Relation.HEAD_OF_STATE.phrase(PLACE_OF_BURIAL_OF_PHRASE),
    f'{Relation.PLACE_OF_BURIAL.name}-{Relation.CONTINENT.name}': Relation.CONTINENT.phrase(PLACE_OF_BURIAL_OF_PHRASE),
    f'{Relation.PLACE_OF_BURIAL.name}-{Relation.CAPITAL.name}': Relation.CAPITAL.phrase(PLACE_OF_BURIAL_OF_PHRASE),
    f'{Relation.PLACE_OF_BURIAL.name}-{Relation.CURRENCY.name}': Relation.CURRENCY.phrase(PLACE_OF_BURIAL_OF_PHRASE),
    f'{Relation.PLACE_OF_BURIAL.name}-{Relation.OFFICIAL_LANGUAGE.name}': Relation.OFFICIAL_LANGUAGE.phrase(PLACE_OF_BURIAL_OF_PHRASE),
    f'{Relation.PLACE_OF_BURIAL.name}-{Relation.ANTHEM.name}': Relation.ANTHEM.phrase(PLACE_OF_BURIAL_OF_PHRASE),

    f'{Relation.COUNTRY.name}-{Relation.HEAD_OF_GOVERNMENT.name}': Relation.HEAD_OF_GOVERNMENT.phrase(COUNTRY_OF_PHRASE),
    f'{Relation.COUNTRY.name}-{Relation.HEAD_OF_STATE.name}': Relation.HEAD_OF_STATE.phrase(COUNTRY_OF_PHRASE),
    f'{Relation.COUNTRY.name}-{Relation.CONTINENT.name}': Relation.CONTINENT.phrase(COUNTRY_OF_PHRASE),
    f'{Relation.COUNTRY.name}-{Relation.CAPITAL.name}': Relation.CAPITAL.phrase(COUNTRY_OF_PHRASE),
    f'{Relation.COUNTRY.name}-{Relation.CURRENCY.name}': Relation.CURRENCY.phrase(COUNTRY_OF_PHRASE),
    f'{Relation.COUNTRY.name}-{Relation.OFFICIAL_LANGUAGE.name}': Relation.OFFICIAL_LANGUAGE.phrase(COUNTRY_OF_PHRASE),
    f'{Relation.COUNTRY.name}-{Relation.ANTHEM.name}': Relation.ANTHEM.phrase(COUNTRY_OF_PHRASE),

    f'{Relation.COUNTRY_OF_CITIZENSHIP.name}-{Relation.HEAD_OF_GOVERNMENT.name}': Relation.HEAD_OF_GOVERNMENT.phrase(COUNTRY_OF_CITIZENSHIP_OF_PHRASE),
    f'{Relation.COUNTRY_OF_CITIZENSHIP.name}-{Relation.HEAD_OF_STATE.name}': Relation.HEAD_OF_STATE.phrase(COUNTRY_OF_CITIZENSHIP_OF_PHRASE),
    f'{Relation.COUNTRY_OF_CITIZENSHIP.name}-{Relation.CONTINENT.name}': Relation.CONTINENT.phrase(COUNTRY_OF_CITIZENSHIP_OF_PHRASE),
    f'{Relation.COUNTRY_OF_CITIZENSHIP.name}-{Relation.CAPITAL.name}': Relation.CAPITAL.phrase(COUNTRY_OF_CITIZENSHIP_OF_PHRASE),
    f'{Relation.COUNTRY_OF_CITIZENSHIP.name}-{Relation.CURRENCY.name}': Relation.CURRENCY.phrase(COUNTRY_OF_CITIZENSHIP_OF_PHRASE),
    f'{Relation.COUNTRY_OF_CITIZENSHIP.name}-{Relation.OFFICIAL_LANGUAGE.name}': Relation.OFFICIAL_LANGUAGE.phrase(COUNTRY_OF_CITIZENSHIP_OF_PHRASE),
    f'{Relation.COUNTRY_OF_CITIZENSHIP.name}-{Relation.ANTHEM.name}': Relation.ANTHEM.phrase(COUNTRY_OF_CITIZENSHIP_OF_PHRASE),

    f'{Relation.CAPITAL_OF.name}-{Relation.HEAD_OF_GOVERNMENT.name}': Relation.HEAD_OF_GOVERNMENT.phrase(CAPITAL_OF_PHRASE),
    f'{Relation.CAPITAL_OF.name}-{Relation.HEAD_OF_STATE.name}': Relation.HEAD_OF_STATE.phrase(CAPITAL_OF_PHRASE),
    f'{Relation.CAPITAL_OF.name}-{Relation.CONTINENT.name}': Relation.CONTINENT.phrase(CAPITAL_OF_PHRASE),
    f'{Relation.CAPITAL_OF.name}-{Relation.CAPITAL.name}': Relation.CAPITAL.phrase(CAPITAL_OF_PHRASE),
    f'{Relation.CAPITAL_OF.name}-{Relation.CURRENCY.name}': Relation.CURRENCY.phrase(CAPITAL_OF_PHRASE),
    f'{Relation.CAPITAL_OF.name}-{Relation.OFFICIAL_LANGUAGE.name}': Relation.OFFICIAL_LANGUAGE.phrase(CAPITAL_OF_PHRASE),
    f'{Relation.CAPITAL_OF.name}-{Relation.ANTHEM.name}': Relation.ANTHEM.phrase(CAPITAL_OF_PHRASE),

    f'{Relation.EMPLOYER.name}-{Relation.FOUNDER.name}': Relation.FOUNDER.phrase(EMPLOYER_OF_PHRASE),
}


def relation_couple_to_key(relation1: Relation, relation2: Relation):
    return f'{relation1.name}-{relation2.name}'


def relation_couple_to_phrase(relation1: Relation, relation2: Relation):
    key_for_dict = relation_couple_to_key(relation1, relation2)
    if key_for_dict not in relation_relation2phrase:
        return None
    return relation_relation2phrase[key_for_dict]
